### ISSUE TITLE
jenkins fir publish使用中文 会上传失败

### ISSUE THREAD

**Issue by chaoslife** [PGYER/fir-cli#333]
在mac命令行中，使用fir publish 中文,ipa没有问题，
在Jenkins内使用同样的脚本 ，发布时报错，英文完全没有问题
请问这种错应该怎么解决呢？

12:24:41 No entry for terminal type "unknown";
12:24:41 using dumb terminal settings.
12:24:42 "\xE9" from ASCII-8BIT to UTF-8
12:24:42 /Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.1/lib/api_tools/default_rest_module.rb:39:in `encode'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.1/lib/api_tools/default_rest_module.rb:39:in `to_json'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.1/lib/api_tools/default_rest_module.rb:39:in `build_similar_post_request'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.1/lib/api_tools/default_rest_module.rb:18:in `block (2 levels) in <module:DefaultRestModule>'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.15/lib/fir/util/publish.rb:139:in `fetch_uploading_info'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.15/lib/fir/util/publish.rb:217:in `initialize_publish_options'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.15/lib/fir/util/publish.rb:15:in `publish'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.15/lib/fir/cli.rb:148:in `publish'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.15/lib/fir/cli.rb:195:in `invoke_command'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
12:24:42 /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.15/bin/fir:8:in `<top (required)>'
12:24:42 /usr/local/bin/fir:23:in `load'
12:24:42 /usr/local/bin/fir:23:in `<main>'

**Comment by chaoslife** [comment]
得到继承大佬的帮助 ，已解决，jenkins配置环境变量
LC_ALL = 'en_US.UTF-8'
LANG    = 'en_US.UTF-8'
LANGUAGE = 'en_US.UTF-8'
解决
